fix: "yarn lint" & "yarn typecheck" errors and warnings
"yarn lint" warnings:
```
\src\domain\app\AppConfig.ts
  37:1  warning  This line has a length of 149.
  Maximum allowed is 120  max-len
```

"yarn typecheck" errors:
```
src/domain/event/enrol/EnrolPage.tsx:104:38 - error TS2345: Argument of
type 'readonly GraphQLFormattedError[]' is not assignable to parameter
of type 'readonly GraphQLError[]'.
  Type 'GraphQLFormattedError' is not assignable to type 'GraphQLError'.

104       if (containsAlreadyJoinedError(error.graphQLErrors)) {
                                         ~~~~~~~~~~~~~~~~~~~

src/domain/event/enrol/EnrolPage.tsx:107:46 - error TS2345: Argument of
type 'readonly GraphQLFormattedError[]' is not assignable to parameter
of type 'readonly GraphQLError[]'.

107       } else if (containsOccurrenceFullError(error.graphQLErrors)) {
                                                 ~~~~~~~~~~~~~~~~~~~

src/domain/event/EventRedirect.tsx:164:5 - error TS2532: Object is
possibly 'undefined'.

164     error.graphQLErrors[0].extensions.code ===
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/domain/event/useSubscribeToFreeSpotNotificationMutation.tsx:38:15 -
error TS2345: Argument of type 'GraphQLFormattedError' is not assignable
to parameter of type 'GraphQLError'.
  Type 'GraphQLFormattedError' is missing the following properties from
  type 'GraphQLError': nodes, source, positions, originalError, and 3
  more.

38               graphQLError,
                 ~~~~~~~~~~~~

src/domain/event/useSubscribeToFreeSpotNotificationMutation.tsx:48:15 -
error TS2345: Argument of type 'GraphQLFormattedError' is not assignable
to parameter of type 'GraphQLError'.

48               graphQLError,
                 ~~~~~~~~~~~~

src/hooks/useRHHCConfig.tsx:32:3 - error TS2322: Type '{ siteName:
string; internalHrefOrigins: string[]; apolloClient:
ApolloClient<NormalizedCacheObject>; currentLanguageCode:
LanguageCodeEnum; ... 11 more ...; meta?: { ...; } | undefined; }' is
not assignable to type 'Config'.
  Types of property 'copy' are incompatible.
    Type '{ breadcrumbNavigationLabel: string; breadcrumbListLabel:
    string; menuToggleAriaLabel: string; skipToContentLabel: string;
    openInExternalDomainAriaLabel: string; openInNewTabAriaLabel:
    string; ... 5 more ...; previous: string; }' is not assignable to
    type '{ breadcrumbNavigationLabel: string; breadcrumbListLabel:
    string; menuButtonLabel: string; menuToggleAriaLabel: string;
    skipToContentLabel: string; openInExternalDomainAriaLabel: string;
    ... 6 more ...; archiveSearch?: { ...; } | undefined; } &
    OptionalTranslationsWithFallbacks'.
      Property 'menuButtonLabel' is missing in type '{
        breadcrumbNavigationLabel: string; breadcrumbListLabel: string;
        menuToggleAriaLabel: string; skipToContentLabel: string;
        openInExternalDomainAriaLabel: string; openInNewTabAriaLabel:
        string; ... 5 more ...; previous: string; }' but required in
        type '{ breadcrumbNavigationLabel: string; breadcrumbListLabel:
        string; menuButtonLabel: string; menuToggleAriaLabel: string;
        skipToContentLabel: string; openInExternalDomainAriaLabel:
        string; ... 6 more ...; archiveSearch?: { ...; } |
        undefined; }'.

32   return useMemo(
     ~~~~~~

  node_modules/react-helsinki-headless-cms/Page-a6bc1174.d.ts:320:9
    320         menuButtonLabel: string;
                ~~~~~~~~~~~~~~~
    'menuButtonLabel' is declared here.
```

refs KK-1322